### ISSUE TITLE
Any idea for the visual TestNG XML file?

### ISSUE THREAD

**Issue by ansonliao** [AutomatedOwl/selenium-java-pom-example#2]
Dear @AutomatedOwl , 
Thanks for sharing the allure report integrated selenium and TestNG sample project.
Notice that you need to prepare the TestNG entire XML file of TestNG and specified the XML in the POM.xml, would like to know, any idea how to handle the visual TestNG XML case?
It means that can't specify the xml file in the POM.xml.

Thanks.

**Comment by ansonliao** [comment]
I tried out the answer, deleted the node `<suiteXmlFiles>` is work.
Thanks.

**Comment by AutomatedOwl** [comment]
Hey @ansonliao , regarding you question, alternatively you can also keep the suiteXmlFiles field and override it as a parameter in the maven commnad:
`mvn  -Dsurefire.suiteXmlFiles=xyz_tests.xml test
`

**Comment by ansonliao** [comment]
@AutomatedOwl 
Thanks for your reply, actually my testng project without any TestNG XML, I scan the whole TestNG project and find out the TestNG `Test` class and method, and then generate the instance `XmlSuite.java` and then pass the instance `XmlSuite` to method `new TestNG().run()`.
